import type { Template } from '@kahoot/shared';

export const templates: Template[] = [
  {
    id: 'general-knowledge-1',
    name: 'General Knowledge',
    description: 'A mix of history, science, and pop culture.',
    category: 'Entertainment',
    subcategory: 'Trivia',
    questions: [
      { id: 'gk-1', type: 'multiple_choice', text: 'What is the capital of France?', choices: ['London', 'Berlin', 'Paris', 'Madrid'], correct: 2, limitMs: 20000 },
      { id: 'gk-2', type: 'multiple_choice', text: 'Which planet is known as the Red Planet?', choices: ['Venus', 'Mars', 'Jupiter', 'Saturn'], correct: 1, limitMs: 20000 },
      { id: 'gk-3', type: 'multiple_choice', text: 'Who wrote "Romeo and Juliet"?', choices: ['Charles Dickens', 'William Shakespeare', 'Mark Twain', 'Jane Austen'], correct: 1, limitMs: 20000 },
      { id: 'gk-4', type: 'multiple_choice', text: 'What is the largest ocean on Earth?', choices: ['Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean'], correct: 3, limitMs: 20000 },
      { id: 'gk-5', type: 'multiple_choice', text: 'Which element has the chemical symbol "O"?', choices: ['Gold', 'Oxygen', 'Silver', 'Iron'], correct: 1, limitMs: 15000 },
      { id: 'gk-6', type: 'multiple_choice', text: 'In what year did the Titanic sink?', choices: ['1912', '1905', '1920', '1898'], correct: 0, limitMs: 20000 },
      { id: 'gk-7', type: 'multiple_choice', text: 'Which country is home to the Kangaroo?', choices: ['South Africa', 'Australia', 'Brazil', 'India'], correct: 1, limitMs: 15000 },
      { id: 'gk-8', type: 'multiple_choice', text: 'Who painted the Mona Lisa?', choices: ['Vincent van Gogh', 'Pablo Picasso', 'Leonardo da Vinci', 'Claude Monet'], correct: 2, limitMs: 20000 },
      { id: 'gk-9', type: 'multiple_choice', text: 'What is the hardest natural substance on Earth?', choices: ['Gold', 'Iron', 'Diamond', 'Quartz'], correct: 2, limitMs: 15000 },
      { id: 'gk-10', type: 'multiple_choice', text: 'Which is the smallest continent in the world?', choices: ['Europe', 'Antarctica', 'South America', 'Australia'], correct: 3, limitMs: 20000 }
    ],
  },
  {
    id: 'tech-trivia-1',
    name: 'Tech History',
    description: 'Test your knowledge of the digital age.',
    category: 'Technology',
    subcategory: 'History',
    questions: [
      { id: 'tech-1', type: 'multiple_choice', text: 'In what year was the first iPhone released?', choices: ['2005', '2007', '2008', '2010'], correct: 1, limitMs: 20000 },
      { id: 'tech-2', type: 'multiple_choice', text: 'Who co-founded Microsoft alongside Bill Gates?', choices: ['Steve Jobs', 'Paul Allen', 'Steve Wozniak', 'Elon Musk'], correct: 1, limitMs: 20000 },
      { id: 'tech-3', type: 'multiple_choice', text: 'What does "WWW" stand for?', choices: ['World Wide Web', 'Web Wide World', 'World Web Wide', 'Wide World Web'], correct: 0, limitMs: 15000 },
      { id: 'tech-4', type: 'multiple_choice', text: 'Which company developed the Java programming language?', choices: ['Microsoft', 'Apple', 'Sun Microsystems', 'IBM'], correct: 2, limitMs: 20000 },
      { id: 'tech-5', type: 'multiple_choice', text: 'What was the first domain name ever registered?', choices: ['google.com', 'symbolics.com', 'apple.com', 'microsoft.com'], correct: 1, limitMs: 20000 },
      { id: 'tech-6', type: 'multiple_choice', text: 'Which programming language was created by Guido van Rossum?', choices: ['Java', 'C++', 'Python', 'Ruby'], correct: 2, limitMs: 15000 },
      { id: 'tech-7', type: 'multiple_choice', text: 'What was the first computer mouse made of?', choices: ['Plastic', 'Wood', 'Metal', 'Glass'], correct: 1, limitMs: 20000 },
      { id: 'tech-8', type: 'multiple_choice', text: 'In tech, what does "RAM" stand for?', choices: ['Read Access Memory', 'Random Access Memory', 'Run Active Module', 'Rapid Area Map'], correct: 1, limitMs: 15000 },
      { id: 'tech-9', type: 'multiple_choice', text: 'Who is known as the mother of computer programming?', choices: ['Grace Hopper', 'Ada Lovelace', 'Sheryl Sandberg', 'Margaret Hamilton'], correct: 1, limitMs: 20000 },
      { id: 'tech-10', type: 'multiple_choice', text: 'What year did Facebook launch?', choices: ['2002', '2004', '2006', '2008'], correct: 1, limitMs: 15000 }
    ],
  },
  {
    id: 'aws-practitioner-1',
    name: 'AWS Cloud Practitioner',
    description: 'Core AWS services and cloud concepts.',
    category: 'Technology',
    subcategory: 'Cloud Computing',
    questions: [
      { id: 'aws-1', type: 'multiple_choice', text: 'Which AWS service is used for scalable object storage?', choices: ['EC2', 'RDS', 'S3', 'Lambda'], correct: 2, limitMs: 20000 },
      { id: 'aws-2', type: 'multiple_choice', text: 'What does the "C" in Amazon EC2 stand for?', choices: ['Cloud', 'Compute', 'Center', 'Control'], correct: 1, limitMs: 20000 },
      { id: 'aws-3', type: 'multiple_choice', text: 'Which AWS service provides a managed Relational Database?', choices: ['DynamoDB', 'RDS', 'Redshift', 'ElastiCache'], correct: 1, limitMs: 20000 },
      { id: 'aws-4', type: 'multiple_choice', text: 'What is the AWS tool used to estimate costs?', choices: ['Pricing Calculator', 'Budgets', 'Cost Explorer', 'Trusted Advisor'], correct: 0, limitMs: 20000 },
      { id: 'aws-5', type: 'multiple_choice', text: 'Which service is used to distribute content with low latency?', choices: ['Route 53', 'CloudFront', 'VPC', 'Direct Connect'], correct: 1, limitMs: 20000 },
      { id: 'aws-6', type: 'multiple_choice', text: 'Which AWS service allows you to run code without provisioning servers?', choices: ['EC2', 'Lambda', 'Elastic Beanstalk', 'Fargate'], correct: 1, limitMs: 20000 },
      { id: 'aws-7', type: 'multiple_choice', text: 'What is the AWS Shared Responsibility Model?', choices: ['AWS manages everything', 'Customer manages everything', 'AWS manages security OF the cloud, Customer IN the cloud'], correct: 2, limitMs: 30000 },
      { id: 'aws-8', type: 'multiple_choice', text: 'Which service helps you find, buy, and deploy software that runs on AWS?', choices: ['AWS Artifact', 'AWS Marketplace', 'AWS Config', 'AWS OpsWorks'], correct: 1, limitMs: 20000 },
      { id: 'aws-9', type: 'multiple_choice', text: 'Which service provides on-demand delivery of IT resources over the internet?', choices: ['Cloud Computing', 'Virtualization', 'Networking', 'Storage'], correct: 0, limitMs: 15000 },
      { id: 'aws-10', type: 'multiple_choice', text: 'What is an AWS Region?', choices: ['A single data center', 'A group of edge locations', 'A physical location with multiple Availability Zones', 'A collection of VPCs'], correct: 2, limitMs: 20000 }
    ],
  },
  {
    id: 'ice-breaker-1',
    name: 'Office Ice Breakers',
    description: 'Get to know your teammates better!',
    category: 'Corporate',
    subcategory: 'Team Building',
    questions: [
      { id: 'ib-1', type: 'multiple_choice', text: 'Which of these is a popular coffee brand?', choices: ['Starbucks', 'Tesla', 'Nike', 'Adobe'], correct: 0, limitMs: 15000 },
      { id: 'ib-2', type: 'multiple_choice', text: 'What is the most common office snack?', choices: ['Apples', 'Pizza', 'Cookies', 'Coffee'], correct: 3, limitMs: 15000 },
      { id: 'ib-3', type: 'multiple_choice', text: 'What is the "best" day for a productive meeting?', choices: ['Monday morning', 'Friday afternoon', 'Tuesday morning', 'Sunday night'], correct: 2, limitMs: 20000 },
      { id: 'ib-4', type: 'multiple_choice', text: 'Which activity is a classic remote team builder?', choices: ['Competitive sleeping', 'Virtual Happy Hour', 'Sending emails', 'Buying stocks'], correct: 1, limitMs: 20000 },
      { id: 'ib-5', type: 'multiple_choice', text: 'What is the most common way to start a virtual meeting?', choices: ['"Can you see my screen?"', '"Let\'s go home"', '"Why are we here?"', '"Silent meditation"'], correct: 0, limitMs: 15000 },
      { id: 'ib-6', type: 'multiple_choice', text: 'Which desk item is most likely to be borrowed and never returned?', choices: ['The monitor', 'A stapler', 'A pen', 'The chair'], correct: 2, limitMs: 15000 },
      { id: 'ib-7', type: 'multiple_choice', text: 'What is the "Golden Rule" of the office kitchen?', choices: ['Eat everything', 'Label your food', 'Leave dishes in the sink', 'Sing loudly'], correct: 1, limitMs: 15000 },
      { id: 'ib-8', type: 'multiple_choice', text: 'How many unread emails are in a "chaotic" inbox?', choices: ['0', '10', '50', '5,000+'], correct: 3, limitMs: 15000 },
      { id: 'ib-9', type: 'multiple_choice', text: 'What is the most popular time for a "quick sync"?', choices: ['5 minutes before end of day', 'Midnight', 'Lunch break', 'During another meeting'], correct: 0, limitMs: 20000 },
      { id: 'ib-10', type: 'multiple_choice', text: 'What do you call a person who always has the best snacks?', choices: ['The Manager', 'The Office Hero', 'The IT Guy', 'The New Intern'], correct: 1, limitMs: 15000 }
    ],
  },
  {
    id: 'gp-basics-1',
    name: 'General Practitioner (GP) Basics',
    description: 'Foundational medical knowledge for primary care.',
    category: 'Healthcare',
    subcategory: 'Medicine',
    questions: [
      { id: 'gp-1', type: 'multiple_choice', text: 'What is the normal resting heart rate for a healthy adult?', choices: ['40-60 bpm', '60-100 bpm', '100-120 bpm', '120-140 bpm'], correct: 1, limitMs: 20000 },
      { id: 'gp-2', type: 'multiple_choice', text: 'Which organ is primarily responsible for filtering blood?', choices: ['Heart', 'Lungs', 'Kidneys', 'Stomach'], correct: 2, limitMs: 20000 },
      { id: 'gp-3', type: 'multiple_choice', text: 'What is the "First Line" treatment for Type 2 Diabetes usually?', choices: ['Insulin', 'Metformin', 'Aspirin', 'Warfarin'], correct: 1, limitMs: 30000 },
      { id: 'gp-4', type: 'multiple_choice', text: 'Which vitamin is produced when skin is exposed to sunlight?', choices: ['Vitamin A', 'Vitamin B12', 'Vitamin C', 'Vitamin D'], correct: 3, limitMs: 20000 },
      { id: 'gp-5', type: 'multiple_choice', text: 'What does "BP" stand for in a clinical setting?', choices: ['Base Pulse', 'Blood Pressure', 'Body Platelet', 'Brain Potency'], correct: 1, limitMs: 15000 },
      { id: 'gp-6', type: 'multiple_choice', text: 'What is the medical term for high blood pressure?', choices: ['Hypotension', 'Hypertension', 'Hyperglycemia', 'Hypoglycemia'], correct: 1, limitMs: 15000 },
      { id: 'gp-7', type: 'multiple_choice', text: 'Which antibiotic was the first to be discovered?', choices: ['Amoxicillin', 'Penicillin', 'Ciprofloxacin', 'Erythromycin'], correct: 1, limitMs: 20000 },
      { id: 'gp-8', type: 'multiple_choice', text: 'What is the primary function of white blood cells?', choices: ['Carry oxygen', 'Clot blood', 'Fight infection', 'Digest food'], correct: 2, limitMs: 15000 },
      { id: 'gp-9', type: 'multiple_choice', text: 'Where is the humerus bone located?', choices: ['Leg', 'Arm', 'Spine', 'Skull'], correct: 1, limitMs: 15000 },
      { id: 'gp-10', type: 'multiple_choice', text: 'What is the common name for the "Trachea"?', choices: ['Voice box', 'Throat', 'Windpipe', 'Gullet'], correct: 2, limitMs: 15000 }
    ],
  },
  {
    id: 'adv-practitioner-1',
    name: 'Advanced Clinical Practice',
    description: 'Advanced assessment and clinical decision making.',
    category: 'Healthcare',
    subcategory: 'Advanced Nursing',
    questions: [
      { id: 'ap-1', type: 'multiple_choice', text: 'What is a hallmark sign of a Tension Pneumothorax?', choices: ['Tracheal deviation', 'Increased appetite', 'Lower back pain', 'Clear lung sounds'], correct: 0, limitMs: 30000 },
      { id: 'ap-2', type: 'multiple_choice', text: 'Which lab value is most critical in assessing Acute Kidney Injury (AKI)?', choices: ['Hemoglobin', 'Creatinine', 'Cholesterol', 'Glucose'], correct: 1, limitMs: 20000 },
      { id: 'ap-3', type: 'multiple_choice', text: 'In the qSOFA score, which of these is NOT a parameter?', choices: ['Respiratory rate', 'Altered mentation', 'Systolic BP', 'Temperature'], correct: 3, limitMs: 30000 },
      { id: 'ap-4', type: 'multiple_choice', text: 'What is the definitive treatment for Ventricular Fibrillation?', choices: ['Amiodarone', 'Chest compressions only', 'Defibrillation', 'Epinephrine only'], correct: 2, limitMs: 20000 },
      { id: 'ap-5', type: 'multiple_choice', text: 'Which cranial nerve is assessed by asking a patient to shrug their shoulders?', choices: ['CN X (Vagus)', 'CN XI (Accessory)', 'CN XII (Hypoglossal)', 'CN IX (Glossopharyngeal)'], correct: 1, limitMs: 20000 },
      { id: 'ap-6', type: 'multiple_choice', text: 'What is the "Terrible Triad" of the knee?', choices: ['ACL, MCL, Medial Meniscus', 'PCL, LCL, Lateral Meniscus', 'ACL, PCL, Patella', 'MCL, LCL, Tibia'], correct: 0, limitMs: 30000 },
      { id: 'ap-7', type: 'multiple_choice', text: 'What is the therapeutic range for INR in a patient with Atrial Fibrillation?', choices: ['1.0-2.0', '2.0-3.0', '3.5-4.5', '5.0-6.0'], correct: 1, limitMs: 20000 },
      { id: 'ap-8', type: 'multiple_choice', text: 'Which physical exam finding is most suggestive of Meningitis?', choices: ['Positive Murphy\'s sign', 'Positive Brudzinski\'s sign', 'Positive McBurney\'s sign', 'Positive Phalen\'s test'], correct: 1, limitMs: 20000 },
      { id: 'ap-9', type: 'multiple_choice', text: 'What is the primary electrolyte abnormality seen in "Diabetes Insipidus"?', choices: ['Hyperkalemia', 'Hyponatremia', 'Hypernatremia', 'Hypocalcemia'], correct: 2, limitMs: 30000 },
      { id: 'ap-10', type: 'multiple_choice', text: 'Which valve is typically heard best at the 5th intercostal space, mid-clavicular line?', choices: ['Aortic', 'Pulmonic', 'Tricuspid', 'Mitral'], correct: 3, limitMs: 20000 }
    ],
  },
  {
    id: 'math-basics-1',
    name: 'Math Foundations',
    description: 'Simple arithmetic and geometry.',
    category: 'Education',
    subcategory: 'Mathematics',
    questions: [
      { id: 'math-1', type: 'multiple_choice', text: 'What is 12 x 12?', choices: ['124', '144', '164', '112'], correct: 1, limitMs: 30000 },
      { id: 'math-2', type: 'multiple_choice', text: 'How many sides does a hexagon have?', choices: ['5', '6', '7', '8'], correct: 1, limitMs: 20000 },
      { id: 'math-3', type: 'multiple_choice', text: 'What is the square root of 81?', choices: ['7', '8', '9', '10'], correct: 2, limitMs: 15000 },
      { id: 'math-4', type: 'multiple_choice', text: 'In a right-angled triangle, what is the longest side called?', choices: ['Adjacent', 'Opposite', 'Hypotenuse', 'Base'], correct: 2, limitMs: 20000 },
      { id: 'math-5', type: 'multiple_choice', text: 'What is 15% of 200?', choices: ['20', '25', '30', '35'], correct: 2, limitMs: 30000 },
      { id: 'math-6', type: 'multiple_choice', text: 'How many degrees are in a circle?', choices: ['180', '270', '360', '450'], correct: 2, limitMs: 15000 },
      { id: 'math-7', type: 'multiple_choice', text: 'What is the value of Pi to two decimal places?', choices: ['3.12', '3.14', '3.16', '3.18'], correct: 1, limitMs: 15000 },
      { id: 'math-8', type: 'multiple_choice', text: 'Solve: 5 + 3 * 2', choices: ['16', '11', '10', '13'], correct: 1, limitMs: 20000 },
      { id: 'math-9', type: 'multiple_choice', text: 'What is the perimeter of a square with side length 5?', choices: ['20', '25', '15', '10'], correct: 0, limitMs: 15000 },
      { id: 'math-10', type: 'multiple_choice', text: 'Which of these is a prime number?', choices: ['4', '9', '11', '15'], correct: 2, limitMs: 15000 }
    ],
  },
];
